export const GET_SEEKER_LISTING_SUCCESS= "GET_SEEKER_LISTING_SUCCESS";
export const  GET_SEEKER_LISTING = "GET_SEEKER_LISTING";
export const  NEW_ARRIVAL_PROVIDER = "NEW_ARRIVAL_PROVIDER";
export const  NEW_ARRIVAL_PROVIDER_SUCCESS = "NEW_ARRIVA_PROVIDER_SUCCESS";
export const  NEW_ARRIVAL_SEEKER = "NEW_ARRIVAL_SEEKER";
export const  NEW_ARRIVAL_SEEKER_SUCCESS = "NEW_ARRIVAL_SEEKER_SUCCESS";