export const GET_SEEKER_LISTING_SUCCESS= "GET_SEEKER_LISTING_SUCCESS";
export const  GET_SEEKER_LISTING = "GET_SEEKER_LISTING";
export const  NEW_ARRIVAL = "NEW_ARRIVAL";
export const  NEW_ARRIVAL_SUCCESS = "NEW_ARRIVAL_SUCCESS";
export const  TOP_RATED = "TOP_RATED";
export const  TOP_RATED_SUCCESS = "TOP_RATED_SUCCESS";