export const LOGIN = "login";
export const LOGOUT = "logout";
export const LOGIN_SUCCESS = "login_success";
export const FORGOT_PASSWORD = 'forgot_password';
export const RESET_PASSWORD = 'reset_password';
export const RESET_PASSWORD_SUCCESS = 'reset_password_success';
export const SET_LOADER ="set_loader";
export const REGISTER = "register";
export const REGISTER_SUCCESS ="register_success"