
export const GET_USER_NOTIFICATION = "get_USER_NOTIFICATION";
export const GET_USER_NOTIFICATION_SUCCESS = "get_USER_NOTIFICATION_success";
export const ON_NOTIFICATION = "ON_NOTIFICATION";
export const ON_NOTIFICATION_SUCCESS = "ON_NOTIFICATION_success";
export const ADD_CARD_DETAILS = "ADD_CARD_DETAILS";
export const GET_CARD_DETAILS = "GET_CARD_DETAILS";
export const GET_CARD_DETAILS_SUCCESS = "GET_CARD_DETAILS_SUCCESS";
