
export const GET_USER_NOTIFICATION = "get_USER_NOTIFICATION";
export const GET_USER_NOTIFICATION_SUCCESS = "get_USER_NOTIFICATION_SUCCESS";
export const ON_NOTIFICATION = "ON_NOTIFICATION";
export const ON_NOTIFICATION_SUCCESS = "ON_NOTIFICATION_success";
export const ADD_CARD_DETAILS = "ADD_CARD_DETAILS";
export const GET_CARD_DETAILS = "GET_CARD_DETAILS";
export const GET_CARD_DETAILS_SUCCESS = "GET_CARD_DETAILS_SUCCESS";
export const GET_BUSINESS_SEEKER = "get_BUSINESS_SEEKER";
export const GET_BUSINESS_SEEKER_SUCCESS = "get_BUSINESS_SEEKER_SUCCESS";
export const SWITCH_ACCOUNT = "SWITCH_ACCOUNT";
export const SWITCH_ACCOUNT_SUCCESS = "SWITCH_ACCOUNT_SUCCESS";