
export const Routes = {
    DashboardOverview: { path: "/dashboard" },
    NewArrivalProvider: { path: "/Newarrivalproviders" },
    TopRatedProviders: { path: "/TopRatedProviders" },
    Recommended: { path: "/recommended" },
    Profile: { path: "/profile" },
    CreateJob: { path: '/createJob' },
    Applicants: { path: '/applicants/:jobId' },
    LogHours: { path: '/loghours/:jobId' },
    LogHoursDetails: { path: '/loghoursdetails/:jobId' },
    UpdateJob: { path: '/updateJob/:id' },
    DetailJob: { path: '/detailJob/:id' },
    MyJobDetail: { path: '/job-management/jobDetail/:id' },
    DetailProvider: { path: '/detailProvider/:id' },
    WorkExperience:  { path: "/workexperience" },
    Achievement:  { path: "/achievement" },
    UserDetail: { path: '/user_management/userDetail' },
    JobDetails: { path: '/jobDetails' },
    PayementMethod: { path: '/PayementMethod' },
    Favourites: { path: '/favourites' },
    Search: { path: '/search' },
    Settings: { path: '/settings' },
    ChangePassword:{path: '/changePassword'},
    TermsandConditions:{path: '/terms'},
    PrivacyPolicyPublic:{path: '/privacy-public'},
    TermsandConditionsPublic:{path: '/terms-public'},
    PrivacyPolicy:{path: '/privacy'},
    Job: { path: '/job' },
    EditProfile: { path: "/profile/editProfile" },
    Transactions: { path: "/transactions" },
    UserManagement: { path: "/user_management" },
    Categories: { path: "/categories" },
    BusinessCategory: { path: "/businessCategory" },
    Categories_Management: { path: "/category-management" },
    Report_Management: { path: "/Report-management" },
    Dispute_Management: { path: "/dispute-management" },
    Job_Management: { path: "/job-management" },
    Users: { path: "/users" },
    EditAdminProfile: { path: "/AdminProfile/editAdminProfile" },
    AdminProfile: { path: "/AdminProfile" },
    Signin: { path: "/" },
    ForgotPassword: { path: "/forgot-password" },
    ResetPassword: { path: "/reset-password" },
    NotFound: { path: "/404" },
    Chat:{path:'/chat'}
};